server:
  port: 8080

info.applicationName: "@project.artifactId@"
info.version: "@project.version@"
info.branch: "@git.branch@"

media-service:
  available-media:
    - titanic
    - avatar
    - interstellar
    - the martian
    - gatsby
    - gladiator
    - braveheart
    - inception
    - memento
    - two and a half men
    - star wars
    - the avengers
    - american sniper
    - john wick
    - the big bang theory
  check-frequency: 60000

omdb:
  apiKey: 69209ae6
  url: http://www.omdbapi.com

