server:
  port: 8080

info.applicationName: "@project.artifactId@"
info.version: "@project.version@"
info.branch: "@git.branch@"

movies-service:
  api-uri: "http://www.omdbapi.com/?apikey=7fcb37fd&r=json&t="
  available-movies:
    - titanic
    - avatar
    - interstellar
    - the martian
    - gatsby
    - gladiator
    - braveheart
    - inception
    - memento
  check-frequency: 60000
  authentication:
    users:
      - username: api
        password: $2a$10$7ZrkGvZRF9ArNukhvYQl.O3bcJ6Nre7m3G71y3MIDxQq.xCfB1HfK
        roles: USER